[package]
name = "clipper"
version = "0.4.0-no-gui"
edition = "2021"

[dependencies]
scrap = "0.5.0"
spin_sleep = "1.1.1"
gif = "0.12.0"
image = "0.24.2"
device_query = "1.1.3"
crossbeam-channel = "0.5.8"
tokio = { version = "1.25.0", features = ["full"] }
indicatif = "0.17.3"