[package]
name = "clipper"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scrap = "0.5.0"
gif = "0.12.0"
egui = "0.20.1"
eframe = "0.20.1"
tokio = { version = "1.25.0", features = ["full"] }